name: "dyups Deploy"
description: "Deploy site with dyups"
inputs:
  ssh-host:
    description: "SSH HOST"
    required: true
  ssh-port:
    description: "SSH Port"
    required: true
  ssh-username:
    description: "SSH Username"
    required: true
  ssh-key:
    description: "SSH private key"
    required: true
  image:
    description: "Docker image name and tag"
    required: true
  container-port:
    description: "Docker container port"
    required: true
  domain:
    description: "Deployed domain name"
    required: true
  dyups-server:
    description: "dyups service domain name"
    required: true
  dyups-token:
    description: "dyups service token"
    required: true
  docker-run:
    description: "Docker run command"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install SSH KEY
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh-key }} 
        known_hosts: unnecessary
        if_key_exists: replace
    - name: Generate deployment scripts
      shell: bash
      run: |
        if [ "$RUNNER_DEBUG" == "1" ]; then
        echo '#!/bin/bash
        docker pull ${{ inputs.image }} \
          && (docker ps -aq --filter "name=dyups-${{ inputs.domain }}" | xargs docker rm -f || echo "Delete fail") \
          && docker_run="${{ inputs.docker-run }}" \
          && docker_run_default='\''docker run -p ${{ inputs.container-port }} --restart=always -d --name "dyups-${{ inputs.domain }}" ${{ inputs.image }}'\'' \
          && if [ "$docker_run" == "" ]; then docker_run=$docker_run_default; fi \
          && eval $docker_run \
          && ip=$(curl -s --max-time 5 ifconfig.me) \
          && port=$(docker ps --filter "name=${{ inputs.domain }}" --format "{{.Ports}}" -a | awk -F ":" "{print \$2}" | awk -F "->" "{print \$1}") \
          && if [ "$ip" == "" ]; then exit 10; fi \
          && if [ "$port" == "" ]; then exit 11; fi \
          && httpcode=$(curl -sL -w '\''%{http_code}'\'' --connect-timeout 3 "127.0.0.1:$port/?r=$RANDOM") \
          && if [ "$httpcode" != "200" ]; then exit 12; fi \
          && echo "{\"address\":\"$ip\",\"port\":$port}"
        ' > /tmp/agent.sh
        else
        echo '#!/bin/bash
        docker pull ${{ inputs.image }} > /dev/null 2>&1 \
          && (docker ps -aq --filter "name=dyups-${{ inputs.domain }}" | xargs docker rm -f || echo "Delete fail") > /dev/null 2>&1 \
          && docker_run="${{ inputs.docker-run }}" \
          && docker_run_default='\''docker run -p ${{ inputs.container-port }} --restart=always -d --name "dyups-${{ inputs.domain }}" ${{ inputs.image }}'\'' \
          && if [ "$docker_run" == "" ]; then docker_run=$docker_run_default; fi \
          && eval $docker_run > /dev/null 2>&1 \
          && ip=$(curl -s --max-time 5 ifconfig.me) \
          && port=$(docker ps --filter "name=${{ inputs.domain }}" --format "{{.Ports}}" -a | awk -F ":" "{print \$2}" | awk -F "->" "{print \$1}") \
          && if [ "$ip" == "" ]; then exit 10; fi \
          && if [ "$port" == "" ]; then exit 11; fi \
          && httpcode=$(curl -sL -w '\''%{http_code}'\'' --connect-timeout 3 "127.0.0.1:$port/?r=$RANDOM" -o /dev/null) \
          && if [ "$httpcode" != "200" ]; then exit 12; fi \
          && echo "{\"address\":\"$ip\",\"port\":$port}"
        ' > /tmp/agent.sh
        fi
        if [ "$RUNNER_DEBUG" == "1" ]; then
          cat /tmp/agent.sh
        fi
    - name: Deploy on a remote machine
      id: deploy
      shell: bash
      run: |
        host=${{ inputs.ssh-host }}
        hosts=(${host//,/ })
        result=""
        for key in "${hosts[@]}"; do
          if [ "$RUNNER_DEBUG" == "1" ]; then
            ssh -p ${{ inputs.ssh-port }} -o StrictHostKeyChecking=no "${{ inputs.ssh-username }}@$key" pwd
          fi
          res=$(ssh -p ${{ inputs.ssh-port }} -o StrictHostKeyChecking=no "${{ inputs.ssh-username }}@$key" 'bash -s' < /tmp/agent.sh)
          code=$?
          if [ "$RUNNER_DEBUG" == "1" ]; then
            echo "code=$code , res=$res"
          fi
          if [ "$code" != "0" ]; then
            echo "$key 部署失败，状态码：$code ，信息：$res"
          else
            if [ "$result" == "" ]; then
              result="$res"
            else
              result="$result,$res"
            fi
          fi
        done
        rm -rf /tmp/agent.sh
        if [ "$RUNNER_DEBUG" == "1" ]; then
          exit 16
        fi
        if [ "$result" == "" ]; then
          echo "没有部署成功"
          exit 13
        fi
        result="[$result]"
        echo "::set-output name=result::$result"
    - name: Register a dyups domain name
      shell: bash
      run: |
          # 注册 dyups ，会自动同步
          dyupsurl="${{ inputs.dyups-server }}/api/${{ inputs.domain }}?r=$RANDOM"
          httpcode=$(curl -sL -w '%{http_code}' -H 'x-dyups-token: ${{ inputs.dyups-token }}' -X POST -d '${{ steps.deploy.outputs.result }}' $dyupsurl -o /dev/null)
          if [ "$httpcode" != "200" ]; then
            echo "注册 dyups 失败，响应码：$httpcode"
            exit 14
          fi
    - name: Test dyups WLB domain
      shell: bash
      run: |
        httpcode=$(curl -sL -w '%{http_code}' --connect-timeout 5 https://${{ inputs.domain }} -o /dev/null)
        if [ "$httpcode" != "200" ]; then
          echo "访问 dyups WLB 错误，响应码：$httpcode"
          exit 15
        fi