name: CI

on:
  push:
    branches: [ master ]

env:
  DOMAIN: kakawoniu.xuexb.com

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test deploy
        uses: ./deploy/
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          image: ${{ secrets.TEST_IMAGE }}
          dyups-server: ${{ secrets.DYUPS_SERVER }}
          dyups-token: ${{ secrets.DYUPS_TOKEN }}
          domain: ${{ secrets.DOMAIN }}
          container-port: 8080
      - name: Test curl
        timeout-minutes: 1
        run: |
          httpcode=`curl -sL -w '%{http_code}' --connect-timeout 5 https://${{ env.DOMAIN }} -o /dev/null`
          if [ "$httpcode" != "200" ]; then
            echo "访问 dyups WLB 错误，响应码：$httpcode"
            exit 1
          fi